sudo: required
dist: trusty
before_install:
    - sudo apt-get install -y git make g++ python3 python3-numpy python3-dev libgoogle-glog-dev verilator
script:
    - cd ./lib/cpp
    - make
    - cd ../../sim/sum_every3
    - make TEST=sm sm_dut -f ../Makefile.verilator
branches:
    only:
        - master
