sudo: required
dist: trusty
before_install:
    - sudo apt-get install -y git make g++ python3 python3-numpy python3-dev libgoogle-glog-dev verilator
script:
    - python3 setup.py install --user
    - cd sim
    - ./test_all_verilator.sh
    - cd standalone
    - ./test_all.sh
branches:
    only:
        - master
